### ISSUE TITLE
Code Pen example (drag select with region) has glitches when copied locally -- no console messages, can't select boxes, and some CSS not working

### ISSUE THREAD

**Issue by bxchang04** [ThibaultJanBeyer/DragSelect#52]
**Describe the bug**
After installing and emulating the https://codepen.io/ThibaultJanBeyer/pen/Nvobgq/ codepen, I get a region with all items stacked on top of each other on the top left of the region. The items are not selectable. (Ps: In my other issue, at least the top item was selectable. See other issue I opened today #51).

**To Reproduce**
1. Go to https://github.com/bxchang04/dragSelectTest
2. Download repo, install DS using npm, then open test2.html
3. See error

**Expected behavior**
Should emulate codepen example with region: https://codepen.io/ThibaultJanBeyer/pen/Nvobgq/ codepen

**Screenshots**
![image](https://user-images.githubusercontent.com/42091866/78508283-85dc0000-7753-11ea-95e3-ed461f2067e6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80.0.3987.163 (Official Build) (64-bit)

**Additional context**
Very similar to my other issue, #51. But at least that project allowed me to select one of the 6 overlapped items (or it may be selecting all 6, but since they are overlapped, I have no way of testing this).

**Comment by bxchang04** [comment]
Fixed it problem above by adding to my HTML file:
<script src="js/ds.js"></script>  

...just above JS script call
<script src = "js/dragSelect2.js"></script>

However my console messages are not appearing in my browser.
![image](https://user-images.githubusercontent.com/42091866/78560373-06e2d800-77e4-11ea-8f21-87a7b8c1bdc1.png)

**Comment by bxchang04** [comment]
update: codepen example has console.log messages for selection, but when I run this code locally, I do not get those messages.

**Comment by ThibaultJanBeyer** [comment]
Hi @bxchang04 and thanks for using DragSelect!

As it seems you forgot to add the DragSelect library. To add a library you've to click on the cogwheel in JS tab and then add the library. See screenshot:
![Screenshot 2020-04-07 at 08 28 55](https://user-images.githubusercontent.com/12467511/78637080-f4cb6d00-78a9-11ea-9062-99f41582fa5e.png)

And your CSS is not working because in my example I used SCSS. That is also something you can change in the settings. Click the cogwheel in CSS tab and select SCSS as the preprocessor. See screenshot:
![Screenshot 2020-04-07 at 08 32 26](https://user-images.githubusercontent.com/12467511/78637348-7ae7b380-78aa-11ea-9f1e-df75fa07bd55.png)

Since this is the second issue opened of this sort. You seem to be just starting out with Web-Development. I would suggest you learn the basics before starting to use any library on Github. The issues section is meant to report bugs in the library, not mistakes in your code. Here are some good places to start learning web-development including HTML, CSS, and JavaScript:

- [Codecademy](codecademy.com/) is an extremely good learning platform for beginners, it will teach you the very basics of most languages in a very good way and it is free (they have a premium account but you won't need it). I used this site heavily to improved my skills 8 years ago.
- [MDN](https://developer.mozilla.org/en-US/docs/Learn) is always a good way to continue, and they have a Learn Web Development section which seems to be good. Although less accessible than Codecademy
- Youtube. Yes, no shit :) once you have the basics with Codecademy, you can start learning specific topics just by searching for it on youtube. You'll find incredibly good tutorials on that platform absolutely free. I.e. [freecodecamp](https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ) and [leveluptuts](https://www.youtube.com/user/LevelUpTuts) are good channels to name a few.

Then, when you own the basics go ahead and play around with libraries and also, after having learned the basics, you can use paid services to improve your skills to a professional level. I like Pluralsight. Udemy has also some good courses. But you could still go completely free just by searching youtube, reading documentation and blog posts on the topic.

I hope that you don't feel offended and appreciate the time I put in here to help you and which you luck and fun for the future, you're on the right track :)

I'll close this now. Feel free to re-open if I'm mistaken and you really find an issue with the library 👍

**Comment by ThibaultJanBeyer** [comment]
And thanks a lot for your donation <3
As you're the first person that ever donated, would you like to be mentioned on the readme page?

**Comment by bxchang04** [comment]
No offense at all. I actually recently completed the Web Dev Full Stack immersive course with CareerFoundry, but they clearly didn't help me go in depth enough with CodePen. Can't thank you enough.

As for my local project, I don't get any console messages but I assume that's because I haven't installed or implemented SASS? I've used SASS once before in a project so please confirm if this is my issue. (repo: https://github.com/bxchang04/dragSelectTest)

I'm really surprised I'm the only person that has donated. This library is brilliant and I wish more people are doing this kind of work in vanilla JS. What's the best way to reach you... do you chat on Gitterly?

**Comment by bxchang04** [comment]
*gitter, not gitterly
