### ISSUE TITLE
Scrolling when using `area` misaligns selection

### ISSUE THREAD

**Issue by emilv** [ThibaultJanBeyer/DragSelect#6]
When using the `area` attribute and you scroll the document, the selection box gets misaligned.

![misaligned-dragselect](https://user-images.githubusercontent.com/1684914/30536704-25453852-9c67-11e7-978e-9218e0f96aa7.png)

[Codepen](https://codepen.io/anon/pen/gGaVOL) demonstrating the problem.

**Comment by ThibaultJanBeyer** [comment]
Thanks a lot for letting me know!
Indeed the body scroll was miscalculating.
This should be fixed in version `1.7.9`.
Please pull the latest version and try again.
It should not produce any regression since I tested it thoroughfully but let me know if you find any.

**Comment by emilv** [comment]
Yup, this solved the problem, thanks! I was just working on the same fix. You forgot to `git push`!

**Comment by ThibaultJanBeyer** [comment]
Oh yes, pushed now.
PS: let me know when you are working on a fix already, so we don’t do work twice :)
